/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.barbosasys.view;

import br.com.barbosasys.controller.CompraController;
import br.com.barbosasys.controller.LancamentoController;
import br.com.barbosasys.controller.ProdutoController;
import br.com.barbosasys.model.Compra;
import br.com.barbosasys.model.Item;
import br.com.barbosasys.model.Lancamento;
import br.com.barbosasys.model.Pessoa;
import br.com.barbosasys.model.Produto;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author helionelys
 */
public class FaturamentoComprasView extends javax.swing.JDialog {

    // Variaveis para armazenar dados da venda
    private int codigoCompra, codTipoPagamento;
    private String nomeFornecedor, dataLancamento, tipoPagamento, valorDesconto,
            dataVencimento, dataPagamento, valorLancamemto;

    Pessoa pessoa = new Pessoa();

    Lancamento lancamentoFaturar = new Lancamento();
    LancamentoController lancamentoController = new LancamentoController();
    ArrayList<Item> listaItensCompras = new ArrayList<>();
    ArrayList<Produto> listaProdutosCompras = new ArrayList<>();
    CompraController compraController = new CompraController();
    Compra compra = new Compra();
    Produto produto = new Produto();
    ProdutoController produtoController = new ProdutoController();

    /**
     * Creates new form FaturamentoView
     */
    public FaturamentoComprasView(ComprasView owner, boolean modal) {
        super(owner, modal);
        initComponents();
        lblCodTipodePagamento.setVisible(false);
        lblCodFornecedor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDataVencimentoCompra = new javax.swing.JFormattedTextField();
        lblValorDesconto = new javax.swing.JLabel();
        lblNumeroDaCompra = new javax.swing.JLabel();
        lblNomeFornecedor = new javax.swing.JLabel();
        lblDataCompra = new javax.swing.JLabel();
        lblTipodePagamentoDescricao = new javax.swing.JLabel();
        lblCodTipodePagamento = new javax.swing.JLabel();
        lblCodFornecedor = new javax.swing.JLabel();
        btnGerarLancamento = new javax.swing.JButton();
        lblValorTotal = new javax.swing.JLabel();
        lbMoneyy = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Assistente de Faturamento de Compras");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel2.setText("Compra:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel3.setText("Cliente:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel4.setText("Data:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel5.setText("Tipo de Pagamento:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel6.setText("Desconto:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel8.setText("Data de Vencimento:");

        try {
            txtDataVencimentoCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVencimentoCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataVencimentoCompra.setCaretColor(new java.awt.Color(153, 0, 0));
        txtDataVencimentoCompra.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N

        lblValorDesconto.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblValorDesconto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorDesconto.setText("lblValorDesconto");

        lblNumeroDaCompra.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblNumeroDaCompra.setText("lblNumeroCompra");

        lblNomeFornecedor.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblNomeFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeFornecedor.setText("lblNomeDoClienteFornecedor");

        lblDataCompra.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblDataCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataCompra.setText("lblDataDaVenda");

        lblTipodePagamentoDescricao.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblTipodePagamentoDescricao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipodePagamentoDescricao.setText("lblTPag");

        lblCodTipodePagamento.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblCodTipodePagamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodTipodePagamento.setText("lblCodTPg");

        lblCodFornecedor.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodTipodePagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(txtDataVencimentoCompra))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblValorDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTipodePagamentoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumeroDaCompra))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNumeroDaCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataCompra)
                    .addComponent(jLabel4)
                    .addComponent(lblCodTipodePagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTipodePagamentoDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblValorDesconto)
                    .addComponent(lblCodFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDataVencimentoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnGerarLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/Money_Calculator_32.png"))); // NOI18N
        btnGerarLancamento.setText("Gerar Lancamento");
        btnGerarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarLancamentoActionPerformed(evt);
            }
        });

        lblValorTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblValorTotal.setForeground(new java.awt.Color(153, 0, 51));
        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorTotal.setText("0,00");

        lbMoneyy.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbMoneyy.setForeground(new java.awt.Color(153, 0, 51));
        lbMoneyy.setText("R$");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMoneyy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGerarLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValorTotal)
                        .addComponent(lbMoneyy)
                        .addComponent(jLabel9))
                    .addComponent(btnGerarLancamento))
                .addGap(25, 25, 25)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnGerarLancamento, lblValorTotal});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarLancamentoActionPerformed
        // TODO add your handling code here:
        this.salvarLancamentoCompras();
    }//GEN-LAST:event_btnGerarLancamentoActionPerformed

//    public int getCodigoCompra() {
//        return codigoCompra;
//    }
//
//    public void setCodigoCompra(int codigoCompra) {
//        this.codigoCompra = codigoCompra;
//    }    
//
//    public int getCodTipoPagamento() {
//        return codTipoPagamento;
//    }
//
//    public void setCodTipoPagamento(int codTipoPagamento) {
//        this.codTipoPagamento = codTipoPagamento;
//    }
//
//    public String getNomeFornecedor() {
//        return nomeFornecedor;
//    }
//
//    public void setNomeFornecedor(String nomeFornecedor) {
//        this.nomeFornecedor = nomeFornecedor;
//    }
//
//    public String getDataLancamento() {
//        return dataLancamento;
//    }
//
//    public void setDataLancamento(String dataLancamento) {
//        this.dataLancamento = dataLancamento;
//    }
//
//    public String getTipoPagamento() {
//        return tipoPagamento;
//    }
//
//    public void setTipoPagamento(String tipoPagamento) {
//        this.tipoPagamento = tipoPagamento;
//    }
//
//    public String getValorDesconto() {
//        return valorDesconto;
//    }
//
//    public void setValorDesconto(String valorDesconto) {
//        this.valorDesconto = valorDesconto;
//    }
//
//    public String getDataVencimento() {
//        return dataVencimento;
//    }
//
//    public void setDataVencimento(String dataVencimento) {
//        this.dataVencimento = dataVencimento;
//    }
//
//    public String getDataPagamento() {
//        return dataPagamento;
//    }
//
//    public void setDataPagamento(String dataPagamento) {
//        this.dataPagamento = dataPagamento;
//    }
//
//    public String getValorLancamemto() {
//        return valorLancamemto;
//    }
//
//    public void setValorLancamemto(String valorLancamemto) {
//        this.valorLancamemto = valorLancamemto;
//    }
    private boolean salvarLancamentoCompras() {
        pessoa.setCodigo(Integer.parseInt(this.lblCodFornecedor.getText()));
        lancamentoFaturar.setPessoa(pessoa);
        compra.setCodCompra(Integer.parseInt(this.lblNumeroDaCompra.getText()));
        String descricaoLancamento = "LANÇAMENTO REFERENTE A COMPRA Nº: " + lblNumeroDaCompra.getText() + " NO VALOR DE: R$ " + lblValorTotal.getText();
        lancamentoFaturar.setDescricaoLancamento(descricaoLancamento);

        String dataLancamento = this.lblDataCompra.getText();
        DateTimeFormatter dataLancamentoRecebida = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter dataLancamentoFormatada = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate = LocalDate.parse(dataLancamento, dataLancamentoRecebida);
        String dataLacamentoBanco = localDate.format(dataLancamentoFormatada);
        lancamentoFaturar.setDataLancamento(dataLacamentoBanco);

        String dataLancamentoVencimento = this.txtDataVencimentoCompra.getText();
        DateTimeFormatter dataRecebida = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter dataFormatada = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate2 = LocalDate.parse(dataLancamentoVencimento, dataRecebida);
        String dataLacamentoVencimentoBanco = localDate2.format(dataFormatada);
        lancamentoFaturar.setDataVencimento(dataLacamentoVencimentoBanco);

        String valorLancamentoOriginal = lblValorTotal.getText();
        String valorLancamentoFormatado = valorLancamentoOriginal.replace(".", "");
        String valorLancamentoFormatado2 = valorLancamentoFormatado.replace(",", ".");
        Double valorBanco = Double.parseDouble(valorLancamentoFormatado2);
        lancamentoFaturar.setValorLancamento(valorBanco);

        lancamentoFaturar.setCodTipoPagamento(Integer.parseInt(lblCodTipodePagamento.getText()));
        lancamentoFaturar.setObservacao("");
        lancamentoFaturar.setCodTipoLancamento(2);
        lancamentoFaturar.setCodStatusLancamento(2);

        int codigoProduto, quantidadeProduto, novaQuantidadeEstoque, quantidadeEstoqueAtual;
        listaItensCompras = compraController.getListaItensCompraController(Integer.parseInt(this.lblNumeroDaCompra.getText()));
        int cont = listaItensCompras.size();
        for (int i = 0; i < cont; i++) {
            Produto objProduto = new Produto();
            codigoProduto = listaItensCompras.get(i).getProduto().getCodProduto();
            quantidadeProduto = listaItensCompras.get(i).getQuantidade();
            //quantidadeEstoqueAtual = produtoController.getProdutoControllerVendaQuantidadeEstoque(listaItensCompras.get(i).getProduto().getCodProduto());
            quantidadeEstoqueAtual = produtoController.getProdutoController(codigoProduto).getQuantidade();
            novaQuantidadeEstoque = quantidadeProduto + quantidadeEstoqueAtual;
            objProduto.setCodProduto(codigoProduto);
            objProduto.setQuantidade(novaQuantidadeEstoque);
            listaProdutosCompras.add(objProduto);
//            System.out.println(listaItensCompras.get(i).getProduto().getCodProduto());
//            System.out.println(listaItensCompras.get(i).getQuantidade());
//            System.out.println(quantidadeEstoqueAtual);
//            System.out.println(novaQuantidadeEstoque);
        }
        produto.setListaItens(listaProdutosCompras);

        if (lancamentoController.salvarLancamentoControllerAPagar(lancamentoFaturar) > 0) {
            produtoController.atualizarProdutoCompraVendaEstoqueController(produto);
            compraController.atualizarComprasFaturamentoController(compra);
            JOptionPane.showMessageDialog(this, "Lancamento incluído com sucesso!");
            JOptionPane.showMessageDialog(this, "Compra Faturada!");

            this.dispose();
            return true;

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            return false;
        }
    }

    public void setLblNumeroCompra(int numeroDaCompra) {
        this.lblNumeroDaCompra.setText(String.valueOf(numeroDaCompra));
    }

    public void setLblCodFornecedor(int codFornecedor) {
        this.lblCodFornecedor.setText(String.valueOf(codFornecedor));
    }

    public void setLblNomeFornecedor(String nomeFornecedor) {
        this.lblNomeFornecedor.setText(String.valueOf(nomeFornecedor));
    }

    public void setLblDataCompra(String dataCompra) {
        this.lblDataCompra.setText(String.valueOf(dataCompra));
    }

    public void setLblCodTipoPagamento(int tipoPagamento) {
        this.lblCodTipodePagamento.setText(String.valueOf(tipoPagamento));
    }

    public void setLblTipoPagamentoDescricao(String tipoPagamentoDescricao) {
        this.lblTipodePagamentoDescricao.setText(String.valueOf(tipoPagamentoDescricao));
    }

    public void setLblValorDesconto(String valorDesconto) {
        this.lblValorDesconto.setText(String.valueOf(valorDesconto));
    }

    public void setLblDataVencimento(String dataCompraVencimento) {
        this.lblDataCompra.setText(String.valueOf(dataCompraVencimento));
    }

    public void setLblValorTotal(String valorTotal) {
        this.lblValorTotal.setText(String.valueOf(valorTotal));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarLancamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbMoneyy;
    private javax.swing.JLabel lblCodFornecedor;
    private javax.swing.JLabel lblCodTipodePagamento;
    private javax.swing.JLabel lblDataCompra;
    private javax.swing.JLabel lblNomeFornecedor;
    private javax.swing.JLabel lblNumeroDaCompra;
    private javax.swing.JLabel lblTipodePagamentoDescricao;
    private javax.swing.JLabel lblValorDesconto;
    private javax.swing.JLabel lblValorTotal;
    protected javax.swing.JFormattedTextField txtDataVencimentoCompra;
    // End of variables declaration//GEN-END:variables
}
