/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.barbosasys.view;

import br.com.barbosasys.controller.ClienteController;
import br.com.barbosasys.controller.FornecedorController;
import br.com.barbosasys.controller.LancamentoController;
import br.com.barbosasys.controller.TipoPagamentoController;
import br.com.barbosasys.model.Cliente;
import br.com.barbosasys.model.Fornecedor;
import br.com.barbosasys.model.Lancamento;
import br.com.barbosasys.model.Pessoa;
import br.com.barbosasys.model.TipoPagamento;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author helionelys
 */
public class FluxoCaixaView extends javax.swing.JDialog {
    Lancamento lancamento = new Lancamento();
    Fornecedor fornecedor = new Fornecedor();
    FornecedorController fornecedorController = new FornecedorController();
    Pessoa pessoa = new Pessoa();
    ArrayList<Lancamento> listaLancamentoAbertos = new ArrayList<>();
    LancamentoController lancamentoController = new LancamentoController();
    TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();
    ArrayList<TipoPagamento> listaTipoPagamentos = new ArrayList<>();
    String tipoCadastro = "cadastro";
    DecimalFormat valoresMonentarios = new DecimalFormat("#,##0.00");
    /**
     * Creates new form FluxoCaixaView
     */
    public FluxoCaixaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarLancamentosAbertos();
        somaEAtualizaValorTotal();
        //somaEAtualizaValorTotal();
        //carregarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFluxoCaixa = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalDespesas = new javax.swing.JLabel();
        lblTotalReceitas = new javax.swing.JLabel();
        lblCenario = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnVisualizarDetalhe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Barbosa Store - Fluxo de Caixa");

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/icon_login.png"))); // NOI18N
        jLabel1.setText("Fluxo de Caixa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblFluxoCaixa.setAutoCreateRowSorter(true);
        tblFluxoCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Cliente/Fornecedor", "Data", "Vencimento", "Valor", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFluxoCaixa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(tblFluxoCaixa);
        if (tblFluxoCaixa.getColumnModel().getColumnCount() > 0) {
            tblFluxoCaixa.getColumnModel().getColumn(0).setMinWidth(60);
            tblFluxoCaixa.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblFluxoCaixa.getColumnModel().getColumn(0).setMaxWidth(60);
            tblFluxoCaixa.getColumnModel().getColumn(1).setMinWidth(230);
            tblFluxoCaixa.getColumnModel().getColumn(1).setPreferredWidth(230);
            tblFluxoCaixa.getColumnModel().getColumn(2).setMinWidth(230);
            tblFluxoCaixa.getColumnModel().getColumn(2).setPreferredWidth(230);
            tblFluxoCaixa.getColumnModel().getColumn(6).setMinWidth(80);
            tblFluxoCaixa.getColumnModel().getColumn(6).setPreferredWidth(80);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores Totais"));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Total Despesa:  R$");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total Receita:  R$");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Cenário:  R$");

        lblTotalDespesas.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblTotalDespesas.setForeground(new java.awt.Color(204, 0, 0));
        lblTotalDespesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalDespesas.setText("lblTotalDespesa");

        lblTotalReceitas.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblTotalReceitas.setForeground(new java.awt.Color(0, 102, 0));
        lblTotalReceitas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalReceitas.setText("lblTotalReceita");

        lblCenario.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblCenario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCenario.setText("lblSaldoCaixa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalDespesas)
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalReceitas)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCenario)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalDespesas)
                    .addComponent(jLabel7)
                    .addComponent(lblTotalReceitas)
                    .addComponent(jLabel8)
                    .addComponent(lblCenario))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/Exit.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVisualizarDetalhe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/Report.png"))); // NOI18N
        btnVisualizarDetalhe.setText("Detalhes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVisualizarDetalhe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnVisualizarDetalhe, jButton1});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnVisualizarDetalhe))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnVisualizarDetalhe, jButton1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void carregarLancamentosAbertos(){
        listaLancamentoAbertos = lancamentoController.getListaLancamentosAbertos();
        DefaultTableModel modelo = (DefaultTableModel) tblFluxoCaixa.getModel();
        modelo.setNumRows(0);
        String nomePessoa = "";
        int cont = listaLancamentoAbertos.size();
        for (int i=0;i < cont; i++){
            //if(listaLancamentoAbertos.get(i).getDescricaoTipoLancamento())
            modelo.addRow(new Object[]{
                listaLancamentoAbertos.get(i).getCodLancamento(),
                listaLancamentoAbertos.get(i).getDescricaoLancamento(),
                listaLancamentoAbertos.get(i).getPessoa().getNomeRazaoSocial(),
                listaLancamentoAbertos.get(i).getDataLancamento(),
                listaLancamentoAbertos.get(i).getDataVencimento(),
                valoresMonentarios.format(listaLancamentoAbertos.get(i).getValorLancamento()),
                listaLancamentoAbertos.get(i).getDescricaoTipoLancamento()
            });
        }
    }
    
        private void somaEAtualizaValorTotal() {
        double totalPagar = 0;
        double totalReceber = 0;
        double valorPagar = 0;
        double valorReceber = 0;
        
        int cont = tblFluxoCaixa.getRowCount();
        for (int i = 0; i < cont; i++) {
            if (tblFluxoCaixa.getValueAt(i, 6).equals("A PAGAR")) {
                String valorPagarOriginal = (String.valueOf(tblFluxoCaixa.getValueAt(i, 5)));
                String valorPagarFormatado = valorPagarOriginal.replace(".", "");
                String valorPagarFormatado2 = valorPagarFormatado.replace(",", ".");
                valorPagar = Double.parseDouble(valorPagarFormatado2);
                totalPagar = valorPagar + totalPagar;
            } else {
                String valorReceberOriginal = (String.valueOf(tblFluxoCaixa.getValueAt(i, 5)));
                String valorReceberFormatado = valorReceberOriginal.replace(".", "");
                String valorReceberFormatado2 = valorReceberFormatado.replace(",", ".");
                valorReceber = Double.parseDouble(valorReceberFormatado2);
                totalReceber = valorReceber + totalReceber;
            }
        }
        lblTotalDespesas.setText(String.valueOf(valoresMonentarios.format(totalPagar)));
        lblTotalReceitas.setText(String.valueOf(valoresMonentarios.format(totalReceber)));
        lblCenario.setText(String.valueOf(valoresMonentarios.format(totalReceber-totalPagar)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizarDetalhe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCenario;
    private javax.swing.JLabel lblTotalDespesas;
    private javax.swing.JLabel lblTotalReceitas;
    private javax.swing.JTable tblFluxoCaixa;
    // End of variables declaration//GEN-END:variables
}
