/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.barbosasys.view;

import br.com.barbosasys.controller.TipoPagamentoController;
import br.com.barbosasys.model.TipoPagamento;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author helionelys
 */
public class Pagamentos2View extends javax.swing.JDialog {

    private Double valorTotal;
    private Double valorDesconto;
    private Double valorRecebido;
    private Double valorTroco;
    private Double valorTotalPagar;
    private String tipoPagamento;

    TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();
    ArrayList<TipoPagamento> listaTipoPagamento = new ArrayList<>();

    public static final int RET_CANCEL = 0;
    public static final int RET_OK = 1;
    private int ponto = 0;
    private int ponto2 = 0;
    private int returnStatus = RET_CANCEL;

    /**
     * Creates new form Pagamentos2View
     */
    public Pagamentos2View(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.carregarTipoPagamento();
        setLocationRelativeTo(null);
        txtDesconto.setTransferHandler(null); //Evitar colar, recortar, etc
        txtValorRecebido.setTransferHandler(null);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTipoPagamento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValorRecebido = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlfValorPagar = new javax.swing.JLabel();
        cbValorAPagar = new javax.swing.JLabel();
        txtValorTroco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnFinalizarPagamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Pagamento:");

        cbTipoPagamento.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Subtotal:");

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Desconto:");

        txtDesconto.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Valor Recebido:");

        txtValorRecebido.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        txtValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorRecebidoKeyTyped(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total a pagar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jlfValorPagar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlfValorPagar.setForeground(new java.awt.Color(0, 153, 102));
        jlfValorPagar.setText(" ");

        cbValorAPagar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cbValorAPagar.setForeground(new java.awt.Color(0, 153, 102));
        cbValorAPagar.setText("R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(cbValorAPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlfValorPagar)
                .addGap(216, 216, 216))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlfValorPagar)
                    .addComponent(cbValorAPagar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        txtValorTroco.setEditable(false);
        txtValorTroco.setBackground(new java.awt.Color(255, 204, 204));
        txtValorTroco.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Troco:");

        btnFinalizarPagamento.setText("Finalizar");
        btnFinalizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(4, 4, 4)
                                .addComponent(txtValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFinalizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFinalizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFinalizarPagamento, txtValorTroco});

        getRootPane().setDefaultButton(btnFinalizarPagamento);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorRecebidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRecebidoKeyTyped
        // TODO add your handling code here:
        this.cbValorAPagar.setText(String.valueOf(this.calcularDesconto()));
        this.txtValorTroco.setText(String.valueOf(this.calcularTroco()));
    }//GEN-LAST:event_txtValorRecebidoKeyTyped

    private void txtDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyReleased
        // TODO add your handling code here:
        this.cbValorAPagar.setText(String.valueOf(this.calcularDesconto()));
        this.txtValorTroco.setText(String.valueOf(this.calcularTroco()));
    }//GEN-LAST:event_txtDescontoKeyReleased

    private void btnFinalizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPagamentoActionPerformed
        // TODO add your handling code here:
        if(this.txtDesconto.getText().equals("")){
            this.valorDesconto = 0.00;
        }else {
            this.valorDesconto = Double.parseDouble(this.txtDesconto.getText());
        }
        this.valorRecebido = Double.parseDouble(this.txtValorRecebido.getText());
        this.valorTroco = Double.parseDouble(this.txtValorTroco.getText());
        this.tipoPagamento = cbTipoPagamento.getSelectedItem().toString();
        if(valorTroco < 0){
            JOptionPane.showMessageDialog(null, "O valor do troco não pode ser menor que 0");
        } else if(Double.parseDouble(cbValorAPagar.getText()) < 0 ){
            JOptionPane.showMessageDialog(null, "O total a pagar deve ser maior que zero");
        }else {
            doClose(RET_OK);
        }
    }//GEN-LAST:event_btnFinalizarPagamentoActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        limparCampos();
        dispose();
    }
    
    private void closeDialog(java.awt.event.WindowEvent evt) {                             
        doClose(RET_CANCEL);
    } 
    
    public int getReturnStatus() {
        return returnStatus;
    }
    
    private void carregarTipoPagamento() {
        listaTipoPagamento = tipoPagamentoController.getListaTipoPagamentoController();
        cbTipoPagamento.removeAllItems();
        for (int i = 0; i < listaTipoPagamento.size(); i++) {
            cbTipoPagamento.addItem(listaTipoPagamento.get(i).getDescricao());
        }
    }

    private Double calcularDesconto() {
        if (!txtSubtotal.getText().trim().equals("")) {
            if (txtSubtotal.getText().isEmpty()) {
                return valorTotal = Double.parseDouble(this.txtSubtotal.getText());
            }
            valorTotal = Float.parseFloat(this.txtSubtotal.getText()) - Double.parseDouble(this.txtDesconto.getText());
            return valorTotal;
        } else {
            return 0.00;
        }
    }

    private Double calcularTroco() {
        if (!txtValorRecebido.getText().equals("")) {
            return Double.parseDouble(this.txtValorRecebido.getText()) - valorTotal;
        } else {
            return 0.00;
        }
    }

    private void limparCampos() {
        txtSubtotal.setText("");
        txtDesconto.setText("");
        txtValorRecebido.setText("");
        txtValorTroco.setText("");
        cbTipoPagamento.setSelectedIndex(0);
        cbValorAPagar.setText("");
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarPagamento;
    private javax.swing.JComboBox cbTipoPagamento;
    private javax.swing.JLabel cbValorAPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlfValorPagar;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtValorRecebido;
    private javax.swing.JTextField txtValorTroco;
    // End of variables declaration//GEN-END:variables

    public Double getValorTotal() {
        return valorTotal;
    }
    
    public void setValorTotoal(Double valorTotal){
        this.valorTotal = valorTotal;
    }
    
    public void setTxtValorTotal(){
        this.txtSubtotal.setText(String.valueOf(this.valorTotal));
    }
    
    public Double getValorDesconto(){
        return valorDesconto;
    }
    
    public void setValorDesconto(Double valorDesconto){
        this.valorDesconto = valorDesconto;
    }
    
    public Double getValorRecebido(){
        return this.valorRecebido;
    }
    
    public void setValorRecebido(Double valorRecebido){
        this.valorRecebido = valorRecebido;
    }
    
    public Double getValorTroco(){
        return valorTroco;
    }
    
    public void setValorTroco(Double valorTroco){
        this.valorTroco = valorTroco;
    }
    
    public Double getValorTotalAPagar(){
        return valorTotalPagar;
    }
    
    public void setValorTotalAPagar(Double valorTotalAPagar){
        this.valorTotalPagar = valorTotalAPagar;
    }
    
    public String getTipoPagamento(){
        return tipoPagamento;
    }
    
    public void setTipoPagamento(String tipoPagamento){
        this.tipoPagamento = tipoPagamento;
    }

}
