package br.com.barbosasys.view;

import br.com.barbosasys.controller.TipoPagamentoController;
import br.com.barbosasys.controller.VendaController;
import br.com.barbosasys.model.Cliente;
import br.com.barbosasys.model.Item;
import br.com.barbosasys.model.Produto;
import br.com.barbosasys.model.TipoPagamento;
import br.com.barbosasys.model.Venda;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author helionelys
 */
public class PagamentosView extends javax.swing.JDialog {

    TipoPagamento tipoPagamento = new TipoPagamento();
    Cliente objClientesPagamentos = new Cliente();
    Venda venda = new Venda();
    Item itemVenda = new Item();
    VendaController vendaController = new VendaController();
    TipoPagamentoController tipoPagamentoController = new TipoPagamentoController();
    ArrayList<TipoPagamento> listaTipoPagamento = new ArrayList<>();
    ArrayList<Item> listaItensVendas = new ArrayList<>();
    double valorRecebido, valorDesconto, valorTroco, valorAReceber;
    DecimalFormat valoresMonentarios = new DecimalFormat("#,##0.00");

    // Itens adicionados no momento das vendas para serem gravados no banco de dados
    DefaultTableModel itensDaVenda;

    /**
     * Creates new form PagamentosView
     */
    public PagamentosView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarTipoPagamento();
        this.txtPagamentoValorDesconto.setText("0,00");
        this.txtPagamentoValorRecebido.setText("0,00");
        this.txtPagamentoValorDesconto.grabFocus();
    }

    private void carregarTipoPagamento() {
        listaTipoPagamento = tipoPagamentoController.getListaTipoPagamentoController();
        cbTipoPagamento.removeAllItems();
        for (int i = 0; i < listaTipoPagamento.size(); i++) {
            cbTipoPagamento.addItem(listaTipoPagamento.get(i).getDescricao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorTroco = new javax.swing.JLabel();
        btnFinalizarPagamento = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalVenda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbTipoPagamento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPagamentoValorRecebido = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPagamentoValorDesconto = new javax.swing.JFormattedTextField();
        lblTotalVendaAReceber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lblValorTroco.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblValorTroco.setForeground(new java.awt.Color(0, 102, 0));
        lblValorTroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTroco.setText("0,00");

        btnFinalizarPagamento.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnFinalizarPagamento.setText("Finalizar");
        btnFinalizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPagamentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel6.setText("Troco:");

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("Total Venda:");

        lblTotalVenda.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTotalVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalVenda.setText("Total Venda");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Pagamento:");

        cbTipoPagamento.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel5.setText("Valor Recebido:");

        txtPagamentoValorRecebido.setBackground(new java.awt.Color(255, 204, 153));
        txtPagamentoValorRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtPagamentoValorRecebido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPagamentoValorRecebido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtPagamentoValorRecebido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPagamentoValorRecebidoMouseClicked(evt);
            }
        });
        txtPagamentoValorRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoValorRecebidoActionPerformed(evt);
            }
        });
        txtPagamentoValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagamentoValorRecebidoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("Desconto:");

        txtPagamentoValorDesconto.setBackground(new java.awt.Color(204, 255, 153));
        txtPagamentoValorDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtPagamentoValorDesconto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPagamentoValorDesconto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtPagamentoValorDesconto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPagamentoValorDescontoMouseClicked(evt);
            }
        });
        txtPagamentoValorDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoValorDescontoActionPerformed(evt);
            }
        });
        txtPagamentoValorDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagamentoValorDescontoKeyTyped(evt);
            }
        });

        lblTotalVendaAReceber.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        lblTotalVendaAReceber.setForeground(new java.awt.Color(153, 0, 51));
        lblTotalVendaAReceber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalVendaAReceber.setText("Total Venda");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel4.setText("Total a Pagar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(lblTotalVendaAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbTipoPagamento, 0, 263, Short.MAX_VALUE)
                                        .addComponent(txtPagamentoValorDesconto))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPagamentoValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTotalVenda)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPagamentoValorDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPagamentoValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotalVendaAReceber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFinalizarPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lblValorTroco)
                        .addComponent(btnFinalizarPagamento))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFinalizarPagamento, jButton1, lblValorTroco});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagamentoValorDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoValorDescontoActionPerformed
        // TODO add your handling code here:
        calcularDesconto();
    }//GEN-LAST:event_txtPagamentoValorDescontoActionPerformed

    private void btnFinalizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPagamentoActionPerformed
        // TODO add your handling code here:
        Venda objVenda = new Venda();
        objVenda.setCodCliente(objClientesPagamentos.getCodigo());
        // Pega a data atual para a venda
        Date agora = new Date();
        SimpleDateFormat dataFormatoAmericano = new SimpleDateFormat("yyyy-MM-dd");
        String datamysql = dataFormatoAmericano.format(agora);

        objVenda.setDataVenda(datamysql);
        // valor do Desconto da venda
        String desconto = this.txtPagamentoValorDesconto.getText();
        String descontoFormatado = desconto.replace(".", "");
        String descontoFormatado2 = descontoFormatado.replace(",", ".");
        Double descontoBanco = Double.parseDouble(descontoFormatado2);
        objVenda.setValorDesconto(descontoBanco);

        // valor Total da Venda
        String valorTotal = this.lblTotalVendaAReceber.getText();
        String totalFormatado = valorTotal.replace(".", "");
        String totalFormatado2 = totalFormatado.replace(",", ".");
        Double totalBanco = Double.parseDouble(totalFormatado2);
        objVenda.setValorTotal(totalBanco);
        objVenda.setCodStatusVenda(1);
        objVenda.setObservacao("Venda realizada pelo PDV na data " + agora +" Com Valor Original de "+ valorTotal);
        objVenda.setTipoPagamento((tipoPagamentoController.getTipoPagamentoController(this.cbTipoPagamento.getSelectedItem().toString()).getCodTipoPagamento()));
        int codigoVenda = vendaController.SalvarVendaController(objVenda);
        
        // Captura o código da ultima venda salva no Banco
            venda.setCodVenda(vendaController.getUltimaVendaDAO());
            
        // Cadastrando os produtos na tabela ItemVendas
        for (int i = 0; i < itensDaVenda.getRowCount(); i++) {
            Item objItemVenda = new Item();
                Produto objProdutoVenda = new Produto();
                objItemVenda.setVenda(venda);
                objProdutoVenda.setCodProduto(Integer.parseInt(itensDaVenda.getValueAt(i, 1).toString()));
                objItemVenda.setProduto(objProdutoVenda);
                objItemVenda.setQuantidade(Integer.parseInt(itensDaVenda.getValueAt(i, 3).toString()));
                //objItemVenda.setSubtotal(Double.parseDouble(itensDaVenda.getValueAt(i, 4).toString()));
                String valorItemProduto = String.valueOf(itensDaVenda.getValueAt(i, 4).toString());
                String vlItemFormatado = valorItemProduto.replace(".", "");
                String vlItemFormatado2 = vlItemFormatado.replace(",", ".");
                Double subTotalBanco = Double.parseDouble(vlItemFormatado2);
                objItemVenda.setSubtotal(subTotalBanco);
                listaItensVendas.add(objItemVenda);
        }
        
        itemVenda.setListaItemVenda(listaItensVendas);
            if (codigoVenda > 0) {
                vendaController.salvarItensVendaController(itemVenda);
                JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
                
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        //JOptionPane.showMessageDialog(null, "Venda efetuada com sucesso");
        this.dispose();
        
    }//GEN-LAST:event_btnFinalizarPagamentoActionPerformed


    private void txtPagamentoValorRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoValorRecebidoActionPerformed
        // TODO add your handling code here:
        calcularTroco();
    }//GEN-LAST:event_txtPagamentoValorRecebidoActionPerformed

    private void txtPagamentoValorDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagamentoValorDescontoKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPagamentoValorDescontoKeyTyped

    private void txtPagamentoValorRecebidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagamentoValorRecebidoKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPagamentoValorRecebidoKeyTyped

    private void txtPagamentoValorDescontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPagamentoValorDescontoMouseClicked
        // TODO add your handling code here:
        this.txtPagamentoValorDesconto.setText(null);
    }//GEN-LAST:event_txtPagamentoValorDescontoMouseClicked

    private void txtPagamentoValorRecebidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPagamentoValorRecebidoMouseClicked
        // TODO add your handling code here:
        this.txtPagamentoValorRecebido.setText(null);

    }//GEN-LAST:event_txtPagamentoValorRecebidoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setLblValorTotal(String valorTotal) {
        this.lblTotalVenda.setText(String.valueOf(valorTotal));
    }

    public void setLblValorTotalAReceber(String valorTotalAReceber) {
        this.lblTotalVendaAReceber.setText(String.valueOf(valorTotalAReceber));
    }

    private void calcularDesconto() {
        String valorVendatela = this.lblTotalVenda.getText();
        String resultadoFormatado = valorVendatela.replace(".", "");
        String resultadoFormatado2 = resultadoFormatado.replace(",", ".");
        Double valorTotalFormatado = Double.parseDouble(resultadoFormatado2);

        String valorDescontoTela = this.txtPagamentoValorDesconto.getText();
        String resultadoFormatado3 = valorDescontoTela.replace(".", "");
        String resultadoFormatado4 = resultadoFormatado3.replace(",", ".");
        Double valorDescontoFormatado = Double.parseDouble(resultadoFormatado4);
        if (valorDescontoFormatado > valorTotalFormatado) {
            JOptionPane.showMessageDialog(this, "O valor do Desconto não pode ser maior que o valor Total da venda");
            this.txtPagamentoValorDesconto.setText(null);
            this.txtPagamentoValorDesconto.grabFocus();
        } else {
            valorAReceber = valorTotalFormatado - valorDescontoFormatado;
            lblTotalVendaAReceber.setText(String.valueOf(valoresMonentarios.format(valorAReceber)));
            this.txtPagamentoValorRecebido.grabFocus();
        }
    }

    private void calcularTroco() {
        String valorTotalARecebertela = this.lblTotalVendaAReceber.getText();
        String resultadoFormatado = valorTotalARecebertela.replace(".", "");
        String resultadoFormatado2 = resultadoFormatado.replace(",", ".");
        Double valorTotalAReceberFormatado = Double.parseDouble(resultadoFormatado2);

        String valorRebidoTela = this.txtPagamentoValorRecebido.getText();
        String resultadoFormatado3 = valorRebidoTela.replace(".", "");
        String resultadoFormatado4 = resultadoFormatado3.replace(",", ".");
        Double valorRecebidoFormatado = Double.parseDouble(resultadoFormatado4);

        valorTroco = valorRecebidoFormatado - valorTotalAReceberFormatado;

        lblValorTroco.setText(String.valueOf(valoresMonentarios.format(valorTroco)));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarPagamento;
    private javax.swing.JComboBox<String> cbTipoPagamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblTotalVenda;
    private javax.swing.JLabel lblTotalVendaAReceber;
    private javax.swing.JLabel lblValorTroco;
    private javax.swing.JFormattedTextField txtPagamentoValorDesconto;
    private javax.swing.JFormattedTextField txtPagamentoValorRecebido;
    // End of variables declaration//GEN-END:variables
}
