/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.barbosasys.view;

import br.com.barbosasys.controller.CategoriaProdutoController;
import br.com.barbosasys.controller.FornecedorController;
import br.com.barbosasys.controller.ProdutoController;
import br.com.barbosasys.controller.UnidadeMedidaController;
import br.com.barbosasys.model.CategoriaProduto;
import br.com.barbosasys.model.Fornecedor;
import br.com.barbosasys.model.Produto;
import br.com.barbosasys.model.UnidadeMedida;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hbarbosa
 */
public class ProdutoView extends javax.swing.JDialog {

    Produto produto = new Produto();
    CategoriaProduto categoriaProduto = new CategoriaProduto();
    UnidadeMedida unidadeMedida = new UnidadeMedida();
    Fornecedor fornecedor = new Fornecedor();

    ProdutoController produtoController = new ProdutoController();
    CategoriaProdutoController categoriaProdutoController = new CategoriaProdutoController();
    UnidadeMedidaController unidadeMedidaController = new UnidadeMedidaController();
    FornecedorController fornecedorController = new FornecedorController();

    ArrayList<Produto> listaProduto = new ArrayList<>();
    ArrayList<CategoriaProduto> listaCategoriaProdutos = new ArrayList<>();
    ArrayList<UnidadeMedida> listaUnidadeMedida = new ArrayList<>();
    ArrayList<Fornecedor> listaForncedor = new ArrayList<>();
    String tipoCadastro;

    /**
     * Creates new form FuncionarioView
     */
    public ProdutoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.carregarProdutos();
        this.carregarCategoriaProduto();
        this.carregarUnidadeMedida();
        this.carregarFornecedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPaneProduto = new javax.swing.JTabbedPane();
        jpBuscaProduto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisaProduto = new javax.swing.JTextField();
        btnIncluirProduto = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        bntExcluirProduto = new javax.swing.JButton();
        btnCancelarProduto = new javax.swing.JButton();
        jpCadastroProduto = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cbStatusProduto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtDataCadastroProduto = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        txtObservacaoProduto = new javax.swing.JTextField();
        btnSalvarProduto = new javax.swing.JButton();
        btnCancelarCadastroProduto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDescricaoProduto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbUnidadeProduto = new javax.swing.JComboBox<>();
        cbCategoriaProduto = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtFabricanteProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbFornecedorProduto = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtValorProduto = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtValorProdutoCompra = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtQtdEstoqueProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Barbosa Store - Produtos");

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Unidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProdutos);
        if (tblProdutos.getColumnModel().getColumnCount() > 0) {
            tblProdutos.getColumnModel().getColumn(0).setMinWidth(80);
            tblProdutos.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblProdutos.getColumnModel().getColumn(0).setMaxWidth(80);
            tblProdutos.getColumnModel().getColumn(1).setMinWidth(400);
            tblProdutos.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblProdutos.getColumnModel().getColumn(1).setMaxWidth(400);
        }

        jLabel1.setText("Descrição:");

        txtPesquisaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaProdutoKeyReleased(evt);
            }
        });

        btnIncluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/produto_incluir.png"))); // NOI18N
        btnIncluirProduto.setText("Incluir");
        btnIncluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirProdutoActionPerformed(evt);
            }
        });

        btnAlterarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/produto_editar.png"))); // NOI18N
        btnAlterarProduto.setText("Alterar");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        bntExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/produto_excluir.png"))); // NOI18N
        bntExcluirProduto.setText("Excluir");
        bntExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirProdutoActionPerformed(evt);
            }
        });

        btnCancelarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/cancelar.png"))); // NOI18N
        btnCancelarProduto.setText("Cancelar");
        btnCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBuscaProdutoLayout = new javax.swing.GroupLayout(jpBuscaProduto);
        jpBuscaProduto.setLayout(jpBuscaProdutoLayout);
        jpBuscaProdutoLayout.setHorizontalGroup(
            jpBuscaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addGroup(jpBuscaProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaProduto))
                    .addGroup(jpBuscaProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIncluirProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntExcluirProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarProduto)))
                .addContainerGap())
        );

        jpBuscaProdutoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bntExcluirProduto, btnAlterarProduto, btnCancelarProduto, btnIncluirProduto});

        jpBuscaProdutoLayout.setVerticalGroup(
            jpBuscaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarProduto)
                    .addComponent(bntExcluirProduto)
                    .addComponent(btnAlterarProduto)
                    .addComponent(btnIncluirProduto))
                .addContainerGap())
        );

        jTabbedPaneProduto.addTab("Busca de Produtos", jpBuscaProduto);

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel8.setText("Código do Produto:");

        txtCodigoProduto.setEditable(false);
        txtCodigoProduto.setFont(new java.awt.Font("Cantarell", 0, 11)); // NOI18N
        txtCodigoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel22.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel22.setText("Status:");

        cbStatusProduto.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        cbStatusProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opção", "1- Ativo", "2- Desativado" }));

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel9.setText("Data do Cadastro:");

        txtDataCadastroProduto.setEditable(false);
        try {
            txtDataCadastroProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCadastroProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataCadastroProduto.setFont(new java.awt.Font("Cantarell", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoProduto)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatusProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cbStatusProduto)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtDataCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Observação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N

        txtObservacaoProduto.setFont(new java.awt.Font("Cantarell", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtObservacaoProduto)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtObservacaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSalvarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/salvar.png"))); // NOI18N
        btnSalvarProduto.setText("Salvar");
        btnSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutoActionPerformed(evt);
            }
        });

        btnCancelarCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/cancelar.png"))); // NOI18N
        btnCancelarCadastroProduto.setText("Cancelar");
        btnCancelarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadastroProdutoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel6.setText("Descrição:");

        txtDescricaoProduto.setFont(new java.awt.Font("Cantarell", 0, 11)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel20.setText("Un. Medida:");

        cbUnidadeProduto.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N

        cbCategoriaProduto.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel21.setText("Fabricante:");

        txtFabricanteProduto.setFont(new java.awt.Font("Cantarell", 0, 11)); // NOI18N
        txtFabricanteProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel10.setText("Fornecedor:");

        cbFornecedorProduto.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel11.setText("Valor:");

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel12.setText("Categoria:");

        txtValorProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtValorProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorProduto.setFont(new java.awt.Font("Cantarell", 0, 11)); // NOI18N
        txtValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorProdutoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel13.setText("Valor Compra:");

        txtValorProdutoCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtValorProdutoCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorProdutoCompra.setFont(new java.awt.Font("Cantarell", 0, 11)); // NOI18N
        txtValorProdutoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorProdutoCompraActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Cantarell", 1, 13)); // NOI18N
        jLabel14.setText("Estoque:");

        txtQtdEstoqueProduto.setEditable(false);
        txtQtdEstoqueProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtDescricaoProduto))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbFornecedorProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFabricanteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtValorProdutoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdEstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoriaProduto)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUnidadeProduto)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFornecedorProduto)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFabricanteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorProdutoCompra)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdEstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jpCadastroProdutoLayout = new javax.swing.GroupLayout(jpCadastroProduto);
        jpCadastroProduto.setLayout(jpCadastroProdutoLayout);
        jpCadastroProdutoLayout.setHorizontalGroup(
            jpCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarCadastroProduto)))
                .addContainerGap())
            .addGroup(jpCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpCadastroProdutoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jpCadastroProdutoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarCadastroProduto, btnSalvarProduto});

        jpCadastroProdutoLayout.setVerticalGroup(
            jpCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroProdutoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCadastroProduto)
                    .addComponent(btnSalvarProduto))
                .addContainerGap())
            .addGroup(jpCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpCadastroProdutoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(344, Short.MAX_VALUE)))
        );

        jTabbedPaneProduto.addTab("Cadastro de Produtos", jpCadastroProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPaneProduto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirProdutoActionPerformed
        // TODO add your handling code here:
        incluirProduto();
        camposAtivados();

    }//GEN-LAST:event_btnIncluirProdutoActionPerformed

    private void btnCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdutoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarProdutoActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        // TODO add your handling code here:
        if (testarSelecao() == true) {
            recuperarProduto();
            camposAtivados();
            tipoCadastro = "alteracao";
        }
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void btnSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutoActionPerformed
        // TODO add your handling code here:
        if (txtDescricaoProduto.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "É necessário atribuir uma descrição ao produto");
            txtDescricaoProduto.grabFocus();
        } else if (tipoCadastro.equals("novo")) {
            salvarProduto();
            carregarProdutos();
            jTabbedPaneProduto.setSelectedIndex(0);
        } else if (tipoCadastro.equals("alteracao")) {
            alterarProduto();
            jTabbedPaneProduto.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btnSalvarProdutoActionPerformed

    private void txtValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorProdutoActionPerformed

    private void btnCancelarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadastroProdutoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarCadastroProdutoActionPerformed

    private void bntExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirProdutoActionPerformed
        // TODO add your handling code here:
        this.excluirProduto();
    }//GEN-LAST:event_bntExcluirProdutoActionPerformed

    private void txtValorProdutoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorProdutoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorProdutoCompraActionPerformed

    private void txtPesquisaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaProdutoKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dadosPesquisar = (DefaultTableModel) this.tblProdutos.getModel();
        final TableRowSorter<TableModel> pesquisa = new TableRowSorter<TableModel>(dadosPesquisar);
        this.tblProdutos.setRowSorter(pesquisa);
        String text = txtPesquisaProduto.getText();
        pesquisa.setRowFilter(RowFilter.regexFilter(text, 1));
    }//GEN-LAST:event_txtPesquisaProdutoKeyReleased

    private void carregarProdutos() {
        listaProduto = produtoController.getListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listaProduto.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaProduto.get(i).getCodProduto(),
                listaProduto.get(i).getDescricao(),
                listaProduto.get(i).getDescricaoUnidadeMedida()
            });
        }
        this.camposDesativados();
    }

    private boolean recuperarProduto() {
        //Armazena a linha selecionada
        int linhaTabela = this.tblProdutos.getSelectedRow();

        //Captura valor código do cliente da linha selecionada
        int codigo = (Integer) tblProdutos.getValueAt(linhaTabela, 0);

        jTabbedPaneProduto.setSelectedIndex(1);
//        cbUnidadeProduto.removeAll();
//        cbCategoriaProduto.removeAll();
//        cbFornecedorProduto.removeAll();
        try {
            // retorna os dados do banco
            produto = produtoController.getProdutoController(codigo);
            this.txtCodigoProduto.setText(String.valueOf(produto.getCodProduto()));
            System.out.println(codigo);

            String dataRetorno = produto.getDataCadastramento();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate localDate = LocalDate.parse(dataRetorno, formatter);
            String dataCadastramentoTela = localDate.format(formatter2);
            this.txtDataCadastroProduto.setText(dataCadastramentoTela);

            this.txtDescricaoProduto.setText(produto.getDescricao());
            this.cbUnidadeProduto.setSelectedItem(unidadeMedidaController.getUnidadeMedidaController(produto.getCodUnidadeMedida()).getDescricao());
            this.cbCategoriaProduto.setSelectedItem(categoriaProdutoController.getCategoriaProdutoController(produto.getCodCategoriaProduto()).getDescricao());

            Double valorRetorno = produto.getValor();
            DecimalFormat df = new DecimalFormat("#,##0.00");
            String valorTela = df.format(valorRetorno);
            this.txtValorProduto.setText(valorTela);
            
            Double valorRetorno2 = produto.getValorCompra();
            DecimalFormat df2 = new DecimalFormat("#,##0.00");
            String valorCompraTela = df2.format(valorRetorno2);
            this.txtValorProdutoCompra.setText(valorCompraTela);

            //System.out.println(valorTela);
            this.cbFornecedorProduto.setSelectedItem(fornecedorController.getFornecedorController(produto.getCodFornecedor()).getNomeRazaoSocial());
            this.txtFabricanteProduto.setText(produto.getFabricante());
            this.txtObservacaoProduto.setText(produto.getObservacao());
            this.txtQtdEstoqueProduto.setText(String.valueOf(produto.getQuantidade()));
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    private void incluirProduto() {
        jTabbedPaneProduto.setSelectedIndex(1);
        camposAtivados();
        txtCodigoProduto.setText("novo");
        txtDataCadastroProduto.setText(null);
        txtDescricaoProduto.setText(null);
        cbCategoriaProduto.setSelectedItem(null);
        txtFabricanteProduto.setText(null);
        cbUnidadeProduto.setSelectedItem(null);
        cbFornecedorProduto.setSelectedItem(null);
        txtObservacaoProduto.setText(null);
        tipoCadastro = "novo";
    }

    private void excluirProduto() {
        if (testarSelecao() == true) {
            int linha = tblProdutos.getSelectedRow();
            String nome = (String) tblProdutos.getValueAt(linha, 1);
            int codigo = (Integer) tblProdutos.getValueAt(linha, 0);

            // Questiona a exclusão
            int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                    + " excluir o registro \nNome: "
                    + nome + " ?", "Atenção", JOptionPane.YES_NO_OPTION);
            //se sim exclui, se não não faz nada    
            if (opcao == JOptionPane.OK_OPTION) {
                if (produtoController.excluirProdutoController(codigo)) {
                    JOptionPane.showMessageDialog(this, "Registro excluído com suscesso!");
                    carregarProdutos();
                    //incluirProduto();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao e os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);

                }
            }
        }
    }

    private boolean alterarProduto() {
        produto.setCodProduto((Integer.parseInt(this.txtCodigoProduto.getText())));
        produto.setDescricao(this.txtDescricaoProduto.getText());
        produto.setCodCategoriaProduto(categoriaProdutoController.getCategoriaProdutoController(this.cbCategoriaProduto.getSelectedItem().toString()).getCodigo());
        produto.setCodUnidadeMedida(unidadeMedidaController.getUnidadeMedidaController(this.cbUnidadeProduto.getSelectedItem().toString()).getCodigo());

        System.out.println(categoriaProdutoController.getCategoriaProdutoController(this.cbCategoriaProduto.getSelectedItem().toString()).getCodigo());
        System.out.println(unidadeMedidaController.getUnidadeMedidaController(this.cbCategoriaProduto.getSelectedItem().toString()).getCodigo());

        String valorProduto = this.txtValorProduto.getText();
        String resultadoFormatado = valorProduto.replace(".", "");
        String resultadoFormatado2 = resultadoFormatado.replace(",", ".");
        Double valorProdutoBancoDados = Double.parseDouble(resultadoFormatado2);
        produto.setValor(valorProdutoBancoDados);
        
        String valorProdutoCompra = this.txtValorProdutoCompra.getText();
        String resultadoFormatado3 = valorProdutoCompra.replace(".", "");
        String resultadoFormatado4 = resultadoFormatado3.replace(",", ".");
        Double valorProdutoCompraBancoDados = Double.parseDouble(resultadoFormatado4);
        produto.setValorCompra(valorProdutoCompraBancoDados);
        
        produto.setCodFornecedor(fornecedorController.getFornecedorController(this.cbFornecedorProduto.getSelectedItem().toString()).getCodigo());
        System.out.println(fornecedorController.getFornecedorController(this.cbFornecedorProduto.getSelectedItem().toString()).getCodigo());
        produto.setFabricante(this.txtFabricanteProduto.getText());
        produto.setObservacao(this.txtObservacaoProduto.getText());

        if (produtoController.atualizarProdutoController(produto)) {
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
            this.incluirProduto();
            this.carregarProdutos();
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean salvarProduto() {

        Date dataCadastramentoCliente = new Date();
        String formatoDataMysql = ("yyyy-MM-dd");
        SimpleDateFormat formatarData = new SimpleDateFormat(formatoDataMysql);
        String dataMysql = formatarData.format(dataCadastramentoCliente);
        produto.setDataCadastramento(dataMysql);
        produto.setDataEstoqueAtualizacao(dataMysql);
        produto.setDescricao(this.txtDescricaoProduto.getText());

        produto.setCodUnidadeMedida(unidadeMedidaController.getUnidadeMedidaController(this.cbUnidadeProduto.getSelectedItem().toString()).getCodigo());
        produto.setCodCategoriaProduto(categoriaProdutoController.getCategoriaProdutoController(this.cbCategoriaProduto.getSelectedItem().toString()).getCodigo());
        String valorProduto = this.txtValorProduto.getText();
        String resultadoFormatado = valorProduto.replace(".", "");
        String resultadoFormatado2 = resultadoFormatado.replace(",", ".");
        Double valorProdutoBancoDados = Double.parseDouble(resultadoFormatado2);
        produto.setValor(valorProdutoBancoDados);
        
        String valorProdutoCompra = this.txtValorProdutoCompra.getText();
        String resultadoFormatado3 = valorProdutoCompra.replace(".", "");
        String resultadoFormatado4 = resultadoFormatado3.replace(",", ".");
        Double valorProdutoCompraBancoDados = Double.parseDouble(resultadoFormatado4);
        produto.setValorCompra(valorProdutoCompraBancoDados);
        
        
        System.out.println(this.txtValorProduto.getText());
        produto.setCodFornecedor(fornecedorController.getFornecedorController(this.cbFornecedorProduto.getSelectedItem().toString()).getCodigo());
        produto.setFabricante(this.txtFabricanteProduto.getText());
        produto.setObservacao(this.txtObservacaoProduto.getText());

        if (produtoController.salvarProdutoController(produto) > 0) {
            JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
            //this.incluirProduto();
            this.carregarProdutos();
            
            
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    }
    
    private void camposDesativados(){
        this.txtCodigoProduto.setEnabled(false);
        this.cbStatusProduto.setEnabled(false);
        this.txtDataCadastroProduto.setEnabled(false);
        this.txtDescricaoProduto.setEnabled(false);
        this.cbUnidadeProduto.setEnabled(false);
        this.cbCategoriaProduto.setEnabled(false);
        this.cbFornecedorProduto.setEnabled(false);
        this.txtFabricanteProduto.setEnabled(false);
        this.txtValorProduto.setEnabled(false);
        this.txtValorProdutoCompra.setEnabled(false);
        this.txtObservacaoProduto.setEnabled(false);
        this.txtObservacaoProduto.setEnabled(false);
        this.btnSalvarProduto.setEnabled(false);
    }
    
    private void camposAtivados(){
        this.txtCodigoProduto.setEnabled(true);
        this.cbStatusProduto.setEnabled(true);
        this.txtDataCadastroProduto.setEnabled(true);
        this.txtDescricaoProduto.setEnabled(true);
        this.cbUnidadeProduto.setEnabled(true);
        this.cbCategoriaProduto.setEnabled(true);
        this.cbFornecedorProduto.setEnabled(true);
        this.txtFabricanteProduto.setEnabled(true);
        this.txtValorProduto.setEnabled(true);
        this.txtValorProdutoCompra.setEnabled(true);
        this.txtObservacaoProduto.setEnabled(true);
        this.txtObservacaoProduto.setEnabled(true);
        this.btnSalvarProduto.setEnabled(true);
    }

    private void carregarUnidadeMedida() {
        listaUnidadeMedida = unidadeMedidaController.getListaUnidadeMedidaController();
        cbUnidadeProduto.removeAllItems();
        for (int i = 0; i < listaUnidadeMedida.size(); i++) {
            cbUnidadeProduto.addItem(listaUnidadeMedida.get(i).getDescricao());
        }
    }

    private void carregarCategoriaProduto() {
        listaCategoriaProdutos = categoriaProdutoController.getListaCategoriaProdutoController();
        cbCategoriaProduto.removeAllItems();
        for (int i = 0; i < listaCategoriaProdutos.size(); i++) {
            cbCategoriaProduto.addItem(listaCategoriaProdutos.get(i).getDescricao());
        }
    }

    private void carregarFornecedor() {
        listaForncedor = fornecedorController.getListaFornecedorController();
        cbFornecedorProduto.removeAllItems();
        for (int i = 0; i < listaForncedor.size(); i++) {
            cbFornecedorProduto.addItem(listaForncedor.get(i).getNomeRazaoSocial());
        }
    }

    private boolean testarSelecao() {
        int selecao = tblProdutos.getSelectedRow();

        if (selecao == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para realizar essa operação.");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FuncionarioView dialog = new FuncionarioView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExcluirProduto;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnCancelarCadastroProduto;
    private javax.swing.JButton btnCancelarProduto;
    private javax.swing.JButton btnIncluirProduto;
    private javax.swing.JButton btnSalvarProduto;
    private javax.swing.JComboBox<String> cbCategoriaProduto;
    private javax.swing.JComboBox<String> cbFornecedorProduto;
    private javax.swing.JComboBox<String> cbStatusProduto;
    private javax.swing.JComboBox<String> cbUnidadeProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneProduto;
    private javax.swing.JPanel jpBuscaProduto;
    private javax.swing.JPanel jpCadastroProduto;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JFormattedTextField txtDataCadastroProduto;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtFabricanteProduto;
    private javax.swing.JTextField txtObservacaoProduto;
    private javax.swing.JTextField txtPesquisaProduto;
    private javax.swing.JTextField txtQtdEstoqueProduto;
    private javax.swing.JFormattedTextField txtValorProduto;
    private javax.swing.JFormattedTextField txtValorProdutoCompra;
    // End of variables declaration//GEN-END:variables

}
