package br.com.barbosasys.view;

import br.com.barbosasys.controller.ClienteController;
import br.com.barbosasys.controller.VendaController;
import br.com.barbosasys.model.Cliente;
import br.com.barbosasys.utilitarios.UtilDatas;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class RelatorioVendasView extends javax.swing.JDialog {

    ArrayList<Cliente> listaClientes = new ArrayList<>();
    ClienteController clienteController = new ClienteController();

    /**
     * Creates new form RelatorioVendasView
     */
    public RelatorioVendasView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarCliente();
        setLocationRelativeTo(null);
        btnGerarRelatorio.setEnabled(false);
        jdcRelatorioDataInicio.setEnabled(false);
        jdcRelatorioDataFim.setEnabled(false);
        cbRelatorioVendaListaClientes.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroupTipoBuscaVenda = new javax.swing.ButtonGroup();
        rbRelatorioVendasPorData = new javax.swing.JRadioButton();
        rbRelatorioVendasPorCliente = new javax.swing.JRadioButton();
        jdcRelatorioDataInicio = new com.toedter.calendar.JDateChooser();
        cbRelatorioVendaListaClientes = new javax.swing.JComboBox<>();
        btnGerarRelatorio = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        rbRelatorioVendasGeral = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jdcRelatorioDataFim = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Barbosa Store - Relatórios Vendas");

        rbGroupTipoBuscaVenda.add(rbRelatorioVendasPorData);
        rbRelatorioVendasPorData.setText("Intervalo datas");
        rbRelatorioVendasPorData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRelatorioVendasPorDataActionPerformed(evt);
            }
        });

        rbGroupTipoBuscaVenda.add(rbRelatorioVendasPorCliente);
        rbRelatorioVendasPorCliente.setText("Buscar Cliente");
        rbRelatorioVendasPorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRelatorioVendasPorClienteActionPerformed(evt);
            }
        });

        btnGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/Report.png"))); // NOI18N
        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbosasys/images/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        rbGroupTipoBuscaVenda.add(rbRelatorioVendasGeral);
        rbRelatorioVendasGeral.setText("Geral");
        rbRelatorioVendasGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRelatorioVendasGeralActionPerformed(evt);
            }
        });

        jLabel1.setText("Geral Relatório com todas vendas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rbRelatorioVendasPorData)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbRelatorioVendasGeral)
                            .addComponent(rbRelatorioVendasPorCliente))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGerarRelatorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jdcRelatorioDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jdcRelatorioDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbRelatorioVendaListaClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnGerarRelatorio});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRelatorioVendasGeral)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRelatorioVendaListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbRelatorioVendasPorCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbRelatorioVendasPorData)
                    .addComponent(jdcRelatorioDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcRelatorioDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnGerarRelatorio))
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnGerarRelatorio});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbRelatorioVendasPorDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRelatorioVendasPorDataActionPerformed
        // TODO add your handling code here:
        btnGerarRelatorio.setEnabled(true);
        jdcRelatorioDataInicio.setEnabled(true);
        jdcRelatorioDataFim.setEnabled(true);
        jdcRelatorioDataInicio.grabFocus();
        cbRelatorioVendaListaClientes.setEnabled(false);
    }//GEN-LAST:event_rbRelatorioVendasPorDataActionPerformed

    private void rbRelatorioVendasPorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRelatorioVendasPorClienteActionPerformed
        // TODO add your handling code here:
        btnGerarRelatorio.setEnabled(true);
        jdcRelatorioDataInicio.setEnabled(false);
        jdcRelatorioDataFim.setEnabled(false);
        cbRelatorioVendaListaClientes.setEnabled(true);

    }//GEN-LAST:event_rbRelatorioVendasPorClienteActionPerformed

    private void rbRelatorioVendasGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRelatorioVendasGeralActionPerformed
        // TODO add your handling code here:
        btnGerarRelatorio.setEnabled(true);
        jdcRelatorioDataInicio.setEnabled(false);
        jdcRelatorioDataFim.setEnabled(false);
        cbRelatorioVendaListaClientes.setEnabled(false);
    }//GEN-LAST:event_rbRelatorioVendasGeralActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        // TODO add your handling code here:
        VendaController vendaController = new VendaController();
        UtilDatas utilDatas = new UtilDatas();
        if (rbRelatorioVendasGeral.isSelected()) {
            vendaController.gerarRelatorioVendasGeral();
        }
        if (rbRelatorioVendasPorCliente.isSelected()) {
            int codigo = (clienteController.getClienteController(this.cbRelatorioVendaListaClientes.getSelectedItem().toString()).getCodigo());
            vendaController.gerarRelatorioVendasPorCliente(codigo);
            System.out.println(codigo);
        }
        if (rbRelatorioVendasPorData.isSelected()) {
            Date dataInicio = null, dataFim = null;
            try {
               dataInicio = utilDatas.TransformaDataParaFormatoAmericanoS((jdcRelatorioDataInicio.getDate()));
               dataFim = utilDatas.TransformaDataParaFormatoAmericanoS((jdcRelatorioDataFim.getDate()));
            } catch (Exception e) {
                Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, e);
            }
            vendaController.gerarRelatorioVendasPorDatas(dataInicio, dataFim);
        }
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void carregarCliente() {
        listaClientes = clienteController.getListaClienteController();
        cbRelatorioVendaListaClientes.removeAllItems();
        for (int i = 0; i < listaClientes.size(); i++) {
            cbRelatorioVendaListaClientes.addItem(listaClientes.get(i).getNomeRazaoSocial());

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JComboBox<String> cbRelatorioVendaListaClientes;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdcRelatorioDataFim;
    private com.toedter.calendar.JDateChooser jdcRelatorioDataInicio;
    private javax.swing.ButtonGroup rbGroupTipoBuscaVenda;
    protected javax.swing.JRadioButton rbRelatorioVendasGeral;
    protected javax.swing.JRadioButton rbRelatorioVendasPorCliente;
    protected javax.swing.JRadioButton rbRelatorioVendasPorData;
    // End of variables declaration//GEN-END:variables
}
